/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents Recent Mention Work Item
 */
@ApiModel(description = "Represents Recent Mention Work Item")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class AccountRecentMentionWorkItemModel {
  public static final String SERIALIZED_NAME_ASSIGNED_TO = "assignedTo";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_TO)
  private String assignedTo;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_MENTIONED_DATE_FIELD = "mentionedDateField";
  @SerializedName(SERIALIZED_NAME_MENTIONED_DATE_FIELD)
  private OffsetDateTime mentionedDateField;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_TEAM_PROJECT = "teamProject";
  @SerializedName(SERIALIZED_NAME_TEAM_PROJECT)
  private String teamProject;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_WORK_ITEM_TYPE = "workItemType";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_TYPE)
  private String workItemType;


  public AccountRecentMentionWorkItemModel assignedTo(String assignedTo) {
    
    this.assignedTo = assignedTo;
    return this;
  }

   /**
   * Assigned To
   * @return assignedTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Assigned To")

  public String getAssignedTo() {
    return assignedTo;
  }


  public void setAssignedTo(String assignedTo) {
    this.assignedTo = assignedTo;
  }


  public AccountRecentMentionWorkItemModel id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Work Item Id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Work Item Id")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public AccountRecentMentionWorkItemModel mentionedDateField(OffsetDateTime mentionedDateField) {
    
    this.mentionedDateField = mentionedDateField;
    return this;
  }

   /**
   * Latest date that the user were mentioned
   * @return mentionedDateField
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Latest date that the user were mentioned")

  public OffsetDateTime getMentionedDateField() {
    return mentionedDateField;
  }


  public void setMentionedDateField(OffsetDateTime mentionedDateField) {
    this.mentionedDateField = mentionedDateField;
  }


  public AccountRecentMentionWorkItemModel state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * State of the work item
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "State of the work item")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    this.state = state;
  }


  public AccountRecentMentionWorkItemModel teamProject(String teamProject) {
    
    this.teamProject = teamProject;
    return this;
  }

   /**
   * Team project the work item belongs to
   * @return teamProject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Team project the work item belongs to")

  public String getTeamProject() {
    return teamProject;
  }


  public void setTeamProject(String teamProject) {
    this.teamProject = teamProject;
  }


  public AccountRecentMentionWorkItemModel title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title of the work item
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Title of the work item")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public AccountRecentMentionWorkItemModel workItemType(String workItemType) {
    
    this.workItemType = workItemType;
    return this;
  }

   /**
   * Type of Work Item
   * @return workItemType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of Work Item")

  public String getWorkItemType() {
    return workItemType;
  }


  public void setWorkItemType(String workItemType) {
    this.workItemType = workItemType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountRecentMentionWorkItemModel accountRecentMentionWorkItemModel = (AccountRecentMentionWorkItemModel) o;
    return Objects.equals(this.assignedTo, accountRecentMentionWorkItemModel.assignedTo) &&
        Objects.equals(this.id, accountRecentMentionWorkItemModel.id) &&
        Objects.equals(this.mentionedDateField, accountRecentMentionWorkItemModel.mentionedDateField) &&
        Objects.equals(this.state, accountRecentMentionWorkItemModel.state) &&
        Objects.equals(this.teamProject, accountRecentMentionWorkItemModel.teamProject) &&
        Objects.equals(this.title, accountRecentMentionWorkItemModel.title) &&
        Objects.equals(this.workItemType, accountRecentMentionWorkItemModel.workItemType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignedTo, id, mentionedDateField, state, teamProject, title, workItemType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountRecentMentionWorkItemModel {\n");
    sb.append("    assignedTo: ").append(toIndentedString(assignedTo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mentionedDateField: ").append(toIndentedString(mentionedDateField)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    teamProject: ").append(toIndentedString(teamProject)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    workItemType: ").append(toIndentedString(workItemType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

