/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.WorkItemReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Defines result of artifact URI query on work items. Contains mapping of work item IDs to artifact URI.
 */
@ApiModel(description = "Defines result of artifact URI query on work items. Contains mapping of work item IDs to artifact URI.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class ArtifactUriQueryResult {
  public static final String SERIALIZED_NAME_ARTIFACT_URIS_QUERY_RESULT = "artifactUrisQueryResult";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_URIS_QUERY_RESULT)
  private Map<String, List<WorkItemReference>> artifactUrisQueryResult = null;


  public ArtifactUriQueryResult artifactUrisQueryResult(Map<String, List<WorkItemReference>> artifactUrisQueryResult) {
    
    this.artifactUrisQueryResult = artifactUrisQueryResult;
    return this;
  }

  public ArtifactUriQueryResult putArtifactUrisQueryResultItem(String key, List<WorkItemReference> artifactUrisQueryResultItem) {
    if (this.artifactUrisQueryResult == null) {
      this.artifactUrisQueryResult = new HashMap<String, List<WorkItemReference>>();
    }
    this.artifactUrisQueryResult.put(key, artifactUrisQueryResultItem);
    return this;
  }

   /**
   * A Dictionary that maps a list of work item references to the given list of artifact URI.
   * @return artifactUrisQueryResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A Dictionary that maps a list of work item references to the given list of artifact URI.")

  public Map<String, List<WorkItemReference>> getArtifactUrisQueryResult() {
    return artifactUrisQueryResult;
  }


  public void setArtifactUrisQueryResult(Map<String, List<WorkItemReference>> artifactUrisQueryResult) {
    this.artifactUrisQueryResult = artifactUrisQueryResult;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactUriQueryResult artifactUriQueryResult = (ArtifactUriQueryResult) o;
    return Objects.equals(this.artifactUrisQueryResult, artifactUriQueryResult.artifactUrisQueryResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactUrisQueryResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactUriQueryResult {\n");
    sb.append("    artifactUrisQueryResult: ").append(toIndentedString(artifactUrisQueryResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

