/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.WorkItemTrackingResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class CommentMention {
  public static final String SERIALIZED_NAME_ARTIFACT_ID = "artifactId";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_ID)
  private String artifactId;

  public static final String SERIALIZED_NAME_ARTIFACT_TYPE = "artifactType";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_TYPE)
  private String artifactType;

  public static final String SERIALIZED_NAME_COMMENT_ID = "commentId";
  @SerializedName(SERIALIZED_NAME_COMMENT_ID)
  private Integer commentId;

  public static final String SERIALIZED_NAME_TARGET_ID = "targetId";
  @SerializedName(SERIALIZED_NAME_TARGET_ID)
  private String targetId;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public CommentMention artifactId(String artifactId) {
    
    this.artifactId = artifactId;
    return this;
  }

   /**
   * The artifact portion of the parsed text. (i.e. the work item&#39;s id)
   * @return artifactId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The artifact portion of the parsed text. (i.e. the work item's id)")

  public String getArtifactId() {
    return artifactId;
  }


  public void setArtifactId(String artifactId) {
    this.artifactId = artifactId;
  }


  public CommentMention artifactType(String artifactType) {
    
    this.artifactType = artifactType;
    return this;
  }

   /**
   * The type the parser assigned to the mention. (i.e. person, work item, etc)
   * @return artifactType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type the parser assigned to the mention. (i.e. person, work item, etc)")

  public String getArtifactType() {
    return artifactType;
  }


  public void setArtifactType(String artifactType) {
    this.artifactType = artifactType;
  }


  public CommentMention commentId(Integer commentId) {
    
    this.commentId = commentId;
    return this;
  }

   /**
   * The comment id of the mention.
   * @return commentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The comment id of the mention.")

  public Integer getCommentId() {
    return commentId;
  }


  public void setCommentId(Integer commentId) {
    this.commentId = commentId;
  }


  public CommentMention targetId(String targetId) {
    
    this.targetId = targetId;
    return this;
  }

   /**
   * The resolved target of the mention. An example of this could be a user&#39;s tfid
   * @return targetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The resolved target of the mention. An example of this could be a user's tfid")

  public String getTargetId() {
    return targetId;
  }


  public void setTargetId(String targetId) {
    this.targetId = targetId;
  }


  public CommentMention url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommentMention commentMention = (CommentMention) o;
    return Objects.equals(this.artifactId, commentMention.artifactId) &&
        Objects.equals(this.artifactType, commentMention.artifactType) &&
        Objects.equals(this.commentId, commentMention.commentId) &&
        Objects.equals(this.targetId, commentMention.targetId) &&
        Objects.equals(this.url, commentMention.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactId, artifactType, commentId, targetId, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommentMention {\n");
    sb.append("    artifactId: ").append(toIndentedString(artifactId)).append("\n");
    sb.append("    artifactType: ").append(toIndentedString(artifactType)).append("\n");
    sb.append("    commentId: ").append(toIndentedString(commentId)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

