/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.WorkItemCommentVersionRef;
import com.azure.dev.api.model.WorkItemRelation;
import com.azure.dev.api.model.WorkItemTrackingResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Describes a work item.
 */
@ApiModel(description = "Describes a work item.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItem {
  public static final String SERIALIZED_NAME_COMMENT_VERSION_REF = "commentVersionRef";
  @SerializedName(SERIALIZED_NAME_COMMENT_VERSION_REF)
  private WorkItemCommentVersionRef commentVersionRef;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private Map<String, Object> fields = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_RELATIONS = "relations";
  @SerializedName(SERIALIZED_NAME_RELATIONS)
  private List<WorkItemRelation> relations = null;

  public static final String SERIALIZED_NAME_REV = "rev";
  @SerializedName(SERIALIZED_NAME_REV)
  private Integer rev;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public WorkItem commentVersionRef(WorkItemCommentVersionRef commentVersionRef) {
    
    this.commentVersionRef = commentVersionRef;
    return this;
  }

   /**
   * Get commentVersionRef
   * @return commentVersionRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkItemCommentVersionRef getCommentVersionRef() {
    return commentVersionRef;
  }


  public void setCommentVersionRef(WorkItemCommentVersionRef commentVersionRef) {
    this.commentVersionRef = commentVersionRef;
  }


  public WorkItem fields(Map<String, Object> fields) {
    
    this.fields = fields;
    return this;
  }

  public WorkItem putFieldsItem(String key, Object fieldsItem) {
    if (this.fields == null) {
      this.fields = new HashMap<String, Object>();
    }
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * Map of field and values for the work item.
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Map of field and values for the work item.")

  public Map<String, Object> getFields() {
    return fields;
  }


  public void setFields(Map<String, Object> fields) {
    this.fields = fields;
  }


  public WorkItem id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The work item ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The work item ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public WorkItem relations(List<WorkItemRelation> relations) {
    
    this.relations = relations;
    return this;
  }

  public WorkItem addRelationsItem(WorkItemRelation relationsItem) {
    if (this.relations == null) {
      this.relations = new ArrayList<WorkItemRelation>();
    }
    this.relations.add(relationsItem);
    return this;
  }

   /**
   * Relations of the work item.
   * @return relations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Relations of the work item.")

  public List<WorkItemRelation> getRelations() {
    return relations;
  }


  public void setRelations(List<WorkItemRelation> relations) {
    this.relations = relations;
  }


  public WorkItem rev(Integer rev) {
    
    this.rev = rev;
    return this;
  }

   /**
   * Revision number of the work item.
   * @return rev
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Revision number of the work item.")

  public Integer getRev() {
    return rev;
  }


  public void setRev(Integer rev) {
    this.rev = rev;
  }


  public WorkItem url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItem workItem = (WorkItem) o;
    return Objects.equals(this.commentVersionRef, workItem.commentVersionRef) &&
        Objects.equals(this.fields, workItem.fields) &&
        Objects.equals(this.id, workItem.id) &&
        Objects.equals(this.relations, workItem.relations) &&
        Objects.equals(this.rev, workItem.rev) &&
        Objects.equals(this.url, workItem.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentVersionRef, fields, id, relations, rev, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItem {\n");
    sb.append("    commentVersionRef: ").append(toIndentedString(commentVersionRef)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

