/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.WorkItemTrackingResourceReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Represents the reference to a specific version of a comment on a Work Item.
 */
@ApiModel(description = "Represents the reference to a specific version of a comment on a Work Item.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemCommentVersionRef {
  public static final String SERIALIZED_NAME_COMMENT_ID = "commentId";
  @SerializedName(SERIALIZED_NAME_COMMENT_ID)
  private Integer commentId;

  public static final String SERIALIZED_NAME_CREATED_IN_REVISION = "createdInRevision";
  @SerializedName(SERIALIZED_NAME_CREATED_IN_REVISION)
  private Integer createdInRevision;

  public static final String SERIALIZED_NAME_IS_DELETED = "isDeleted";
  @SerializedName(SERIALIZED_NAME_IS_DELETED)
  private Boolean isDeleted;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public WorkItemCommentVersionRef commentId(Integer commentId) {
    
    this.commentId = commentId;
    return this;
  }

   /**
   * The id assigned to the comment.
   * @return commentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id assigned to the comment.")

  public Integer getCommentId() {
    return commentId;
  }


  public void setCommentId(Integer commentId) {
    this.commentId = commentId;
  }


  public WorkItemCommentVersionRef createdInRevision(Integer createdInRevision) {
    
    this.createdInRevision = createdInRevision;
    return this;
  }

   /**
   * [Internal] The work item revision where this comment was originally added.
   * @return createdInRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "[Internal] The work item revision where this comment was originally added.")

  public Integer getCreatedInRevision() {
    return createdInRevision;
  }


  public void setCreatedInRevision(Integer createdInRevision) {
    this.createdInRevision = createdInRevision;
  }


  public WorkItemCommentVersionRef isDeleted(Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

   /**
   * [Internal] Specifies whether comment was deleted.
   * @return isDeleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "[Internal] Specifies whether comment was deleted.")

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  public void setIsDeleted(Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public WorkItemCommentVersionRef text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * [Internal] The text of the comment.
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "[Internal] The text of the comment.")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public WorkItemCommentVersionRef version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * The version number.
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The version number.")

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }


  public WorkItemCommentVersionRef url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemCommentVersionRef workItemCommentVersionRef = (WorkItemCommentVersionRef) o;
    return Objects.equals(this.commentId, workItemCommentVersionRef.commentId) &&
        Objects.equals(this.createdInRevision, workItemCommentVersionRef.createdInRevision) &&
        Objects.equals(this.isDeleted, workItemCommentVersionRef.isDeleted) &&
        Objects.equals(this.text, workItemCommentVersionRef.text) &&
        Objects.equals(this.version, workItemCommentVersionRef.version) &&
        Objects.equals(this.url, workItemCommentVersionRef.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentId, createdInRevision, isDeleted, text, version, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemCommentVersionRef {\n");
    sb.append("    commentId: ").append(toIndentedString(commentId)).append("\n");
    sb.append("    createdInRevision: ").append(toIndentedString(createdInRevision)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

