/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A work artifact link describes an outbound artifact link type.
 */
@ApiModel(description = "A work artifact link describes an outbound artifact link type.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkArtifactLink {
  public static final String SERIALIZED_NAME_ARTIFACT_TYPE = "artifactType";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_TYPE)
  private String artifactType;

  public static final String SERIALIZED_NAME_LINK_TYPE = "linkType";
  @SerializedName(SERIALIZED_NAME_LINK_TYPE)
  private String linkType;

  public static final String SERIALIZED_NAME_TOOL_TYPE = "toolType";
  @SerializedName(SERIALIZED_NAME_TOOL_TYPE)
  private String toolType;


  public WorkArtifactLink artifactType(String artifactType) {
    
    this.artifactType = artifactType;
    return this;
  }

   /**
   * Target artifact type.
   * @return artifactType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Target artifact type.")

  public String getArtifactType() {
    return artifactType;
  }


  public void setArtifactType(String artifactType) {
    this.artifactType = artifactType;
  }


  public WorkArtifactLink linkType(String linkType) {
    
    this.linkType = linkType;
    return this;
  }

   /**
   * Outbound link type.
   * @return linkType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Outbound link type.")

  public String getLinkType() {
    return linkType;
  }


  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }


  public WorkArtifactLink toolType(String toolType) {
    
    this.toolType = toolType;
    return this;
  }

   /**
   * Target tool type.
   * @return toolType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Target tool type.")

  public String getToolType() {
    return toolType;
  }


  public void setToolType(String toolType) {
    this.toolType = toolType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkArtifactLink workArtifactLink = (WorkArtifactLink) o;
    return Objects.equals(this.artifactType, workArtifactLink.artifactType) &&
        Objects.equals(this.linkType, workArtifactLink.linkType) &&
        Objects.equals(this.toolType, workArtifactLink.toolType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactType, linkType, toolType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkArtifactLink {\n");
    sb.append("    artifactType: ").append(toIndentedString(artifactType)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    toolType: ").append(toIndentedString(toolType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

