/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Describes an update to a work item field.
 */
@ApiModel(description = "Describes an update to a work item field.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemFieldUpdate {
  public static final String SERIALIZED_NAME_NEW_VALUE = "newValue";
  @SerializedName(SERIALIZED_NAME_NEW_VALUE)
  private Object newValue;

  public static final String SERIALIZED_NAME_OLD_VALUE = "oldValue";
  @SerializedName(SERIALIZED_NAME_OLD_VALUE)
  private Object oldValue;


  public WorkItemFieldUpdate newValue(Object newValue) {
    
    this.newValue = newValue;
    return this;
  }

   /**
   * The new value of the field.
   * @return newValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The new value of the field.")

  public Object getNewValue() {
    return newValue;
  }


  public void setNewValue(Object newValue) {
    this.newValue = newValue;
  }


  public WorkItemFieldUpdate oldValue(Object oldValue) {
    
    this.oldValue = oldValue;
    return this;
  }

   /**
   * The old value of the field.
   * @return oldValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The old value of the field.")

  public Object getOldValue() {
    return oldValue;
  }


  public void setOldValue(Object oldValue) {
    this.oldValue = oldValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemFieldUpdate workItemFieldUpdate = (WorkItemFieldUpdate) o;
    return Objects.equals(this.newValue, workItemFieldUpdate.newValue) &&
        Objects.equals(this.oldValue, workItemFieldUpdate.oldValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newValue, oldValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemFieldUpdate {\n");
    sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
    sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

