/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Describes a work item type&#39;s colors.
 */
@ApiModel(description = "Describes a work item type's colors.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemTypeColor {
  public static final String SERIALIZED_NAME_PRIMARY_COLOR = "primaryColor";
  @SerializedName(SERIALIZED_NAME_PRIMARY_COLOR)
  private String primaryColor;

  public static final String SERIALIZED_NAME_SECONDARY_COLOR = "secondaryColor";
  @SerializedName(SERIALIZED_NAME_SECONDARY_COLOR)
  private String secondaryColor;

  public static final String SERIALIZED_NAME_WORK_ITEM_TYPE_NAME = "workItemTypeName";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_TYPE_NAME)
  private String workItemTypeName;


  public WorkItemTypeColor primaryColor(String primaryColor) {
    
    this.primaryColor = primaryColor;
    return this;
  }

   /**
   * Gets or sets the color of the primary.
   * @return primaryColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gets or sets the color of the primary.")

  public String getPrimaryColor() {
    return primaryColor;
  }


  public void setPrimaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
  }


  public WorkItemTypeColor secondaryColor(String secondaryColor) {
    
    this.secondaryColor = secondaryColor;
    return this;
  }

   /**
   * Gets or sets the color of the secondary.
   * @return secondaryColor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gets or sets the color of the secondary.")

  public String getSecondaryColor() {
    return secondaryColor;
  }


  public void setSecondaryColor(String secondaryColor) {
    this.secondaryColor = secondaryColor;
  }


  public WorkItemTypeColor workItemTypeName(String workItemTypeName) {
    
    this.workItemTypeName = workItemTypeName;
    return this;
  }

   /**
   * The name of the work item type.
   * @return workItemTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the work item type.")

  public String getWorkItemTypeName() {
    return workItemTypeName;
  }


  public void setWorkItemTypeName(String workItemTypeName) {
    this.workItemTypeName = workItemTypeName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemTypeColor workItemTypeColor = (WorkItemTypeColor) o;
    return Objects.equals(this.primaryColor, workItemTypeColor.primaryColor) &&
        Objects.equals(this.secondaryColor, workItemTypeColor.secondaryColor) &&
        Objects.equals(this.workItemTypeName, workItemTypeColor.workItemTypeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primaryColor, secondaryColor, workItemTypeName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemTypeColor {\n");
    sb.append("    primaryColor: ").append(toIndentedString(primaryColor)).append("\n");
    sb.append("    secondaryColor: ").append(toIndentedString(secondaryColor)).append("\n");
    sb.append("    workItemTypeName: ").append(toIndentedString(workItemTypeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

