/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.IdentityReference;
import com.azure.dev.api.model.WorkItemTrackingResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Comment on Work Item
 */
@ApiModel(description = "Comment on Work Item")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemComment {
  public static final String SERIALIZED_NAME_REVISED_BY = "revisedBy";
  @SerializedName(SERIALIZED_NAME_REVISED_BY)
  private IdentityReference revisedBy;

  public static final String SERIALIZED_NAME_REVISED_DATE = "revisedDate";
  @SerializedName(SERIALIZED_NAME_REVISED_DATE)
  private OffsetDateTime revisedDate;

  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private Integer revision;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public WorkItemComment revisedBy(IdentityReference revisedBy) {
    
    this.revisedBy = revisedBy;
    return this;
  }

   /**
   * Get revisedBy
   * @return revisedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IdentityReference getRevisedBy() {
    return revisedBy;
  }


  public void setRevisedBy(IdentityReference revisedBy) {
    this.revisedBy = revisedBy;
  }


  public WorkItemComment revisedDate(OffsetDateTime revisedDate) {
    
    this.revisedDate = revisedDate;
    return this;
  }

   /**
   * The date of comment.
   * @return revisedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of comment.")

  public OffsetDateTime getRevisedDate() {
    return revisedDate;
  }


  public void setRevisedDate(OffsetDateTime revisedDate) {
    this.revisedDate = revisedDate;
  }


  public WorkItemComment revision(Integer revision) {
    
    this.revision = revision;
    return this;
  }

   /**
   * The work item revision number.
   * @return revision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The work item revision number.")

  public Integer getRevision() {
    return revision;
  }


  public void setRevision(Integer revision) {
    this.revision = revision;
  }


  public WorkItemComment text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * The text of the comment.
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The text of the comment.")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public WorkItemComment url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemComment workItemComment = (WorkItemComment) o;
    return Objects.equals(this.revisedBy, workItemComment.revisedBy) &&
        Objects.equals(this.revisedDate, workItemComment.revisedDate) &&
        Objects.equals(this.revision, workItemComment.revision) &&
        Objects.equals(this.text, workItemComment.text) &&
        Objects.equals(this.url, workItemComment.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(revisedBy, revisedDate, revision, text, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemComment {\n");
    sb.append("    revisedBy: ").append(toIndentedString(revisedBy)).append("\n");
    sb.append("    revisedDate: ").append(toIndentedString(revisedDate)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

