/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.IdentityReference;
import com.azure.dev.api.model.WorkItemFieldUpdate;
import com.azure.dev.api.model.WorkItemRelationUpdates;
import com.azure.dev.api.model.WorkItemTrackingResource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * Describes an update to a work item.
 */
@ApiModel(description = "Describes an update to a work item.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemUpdate {
  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private Map<String, WorkItemFieldUpdate> fields = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_RELATIONS = "relations";
  @SerializedName(SERIALIZED_NAME_RELATIONS)
  private WorkItemRelationUpdates relations;

  public static final String SERIALIZED_NAME_REV = "rev";
  @SerializedName(SERIALIZED_NAME_REV)
  private Integer rev;

  public static final String SERIALIZED_NAME_REVISED_BY = "revisedBy";
  @SerializedName(SERIALIZED_NAME_REVISED_BY)
  private IdentityReference revisedBy;

  public static final String SERIALIZED_NAME_REVISED_DATE = "revisedDate";
  @SerializedName(SERIALIZED_NAME_REVISED_DATE)
  private OffsetDateTime revisedDate;

  public static final String SERIALIZED_NAME_WORK_ITEM_ID = "workItemId";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_ID)
  private Integer workItemId;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public WorkItemUpdate fields(Map<String, WorkItemFieldUpdate> fields) {
    
    this.fields = fields;
    return this;
  }

  public WorkItemUpdate putFieldsItem(String key, WorkItemFieldUpdate fieldsItem) {
    if (this.fields == null) {
      this.fields = new HashMap<String, WorkItemFieldUpdate>();
    }
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * List of updates to fields.
   * @return fields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of updates to fields.")

  public Map<String, WorkItemFieldUpdate> getFields() {
    return fields;
  }


  public void setFields(Map<String, WorkItemFieldUpdate> fields) {
    this.fields = fields;
  }


  public WorkItemUpdate id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID of update.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID of update.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public WorkItemUpdate relations(WorkItemRelationUpdates relations) {
    
    this.relations = relations;
    return this;
  }

   /**
   * Get relations
   * @return relations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkItemRelationUpdates getRelations() {
    return relations;
  }


  public void setRelations(WorkItemRelationUpdates relations) {
    this.relations = relations;
  }


  public WorkItemUpdate rev(Integer rev) {
    
    this.rev = rev;
    return this;
  }

   /**
   * The revision number of work item update.
   * @return rev
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The revision number of work item update.")

  public Integer getRev() {
    return rev;
  }


  public void setRev(Integer rev) {
    this.rev = rev;
  }


  public WorkItemUpdate revisedBy(IdentityReference revisedBy) {
    
    this.revisedBy = revisedBy;
    return this;
  }

   /**
   * Get revisedBy
   * @return revisedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IdentityReference getRevisedBy() {
    return revisedBy;
  }


  public void setRevisedBy(IdentityReference revisedBy) {
    this.revisedBy = revisedBy;
  }


  public WorkItemUpdate revisedDate(OffsetDateTime revisedDate) {
    
    this.revisedDate = revisedDate;
    return this;
  }

   /**
   * The work item updates revision date.
   * @return revisedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The work item updates revision date.")

  public OffsetDateTime getRevisedDate() {
    return revisedDate;
  }


  public void setRevisedDate(OffsetDateTime revisedDate) {
    this.revisedDate = revisedDate;
  }


  public WorkItemUpdate workItemId(Integer workItemId) {
    
    this.workItemId = workItemId;
    return this;
  }

   /**
   * The work item ID.
   * @return workItemId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The work item ID.")

  public Integer getWorkItemId() {
    return workItemId;
  }


  public void setWorkItemId(Integer workItemId) {
    this.workItemId = workItemId;
  }


  public WorkItemUpdate url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemUpdate workItemUpdate = (WorkItemUpdate) o;
    return Objects.equals(this.fields, workItemUpdate.fields) &&
        Objects.equals(this.id, workItemUpdate.id) &&
        Objects.equals(this.relations, workItemUpdate.relations) &&
        Objects.equals(this.rev, workItemUpdate.rev) &&
        Objects.equals(this.revisedBy, workItemUpdate.revisedBy) &&
        Objects.equals(this.revisedDate, workItemUpdate.revisedDate) &&
        Objects.equals(this.workItemId, workItemUpdate.workItemId) &&
        Objects.equals(this.url, workItemUpdate.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fields, id, relations, rev, revisedBy, revisedDate, workItemId, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemUpdate {\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    rev: ").append(toIndentedString(rev)).append("\n");
    sb.append("    revisedBy: ").append(toIndentedString(revisedBy)).append("\n");
    sb.append("    revisedDate: ").append(toIndentedString(revisedDate)).append("\n");
    sb.append("    workItemId: ").append(toIndentedString(workItemId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

