/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Describes the next state for a work item.
 */
@ApiModel(description = "Describes the next state for a work item.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemNextStateOnTransition {
  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  private String errorCode;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_STATE_ON_TRANSITION = "stateOnTransition";
  @SerializedName(SERIALIZED_NAME_STATE_ON_TRANSITION)
  private String stateOnTransition;


  public WorkItemNextStateOnTransition errorCode(String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Error code if there is no next state transition possible.
   * @return errorCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error code if there is no next state transition possible.")

  public String getErrorCode() {
    return errorCode;
  }


  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  public WorkItemNextStateOnTransition id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Work item ID.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Work item ID.")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public WorkItemNextStateOnTransition message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Error message if there is no next state transition possible.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error message if there is no next state transition possible.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public WorkItemNextStateOnTransition stateOnTransition(String stateOnTransition) {
    
    this.stateOnTransition = stateOnTransition;
    return this;
  }

   /**
   * Name of the next state on transition.
   * @return stateOnTransition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the next state on transition.")

  public String getStateOnTransition() {
    return stateOnTransition;
  }


  public void setStateOnTransition(String stateOnTransition) {
    this.stateOnTransition = stateOnTransition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemNextStateOnTransition workItemNextStateOnTransition = (WorkItemNextStateOnTransition) o;
    return Objects.equals(this.errorCode, workItemNextStateOnTransition.errorCode) &&
        Objects.equals(this.id, workItemNextStateOnTransition.id) &&
        Objects.equals(this.message, workItemNextStateOnTransition.message) &&
        Objects.equals(this.stateOnTransition, workItemNextStateOnTransition.stateOnTransition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, id, message, stateOnTransition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemNextStateOnTransition {\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    stateOnTransition: ").append(toIndentedString(stateOnTransition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

