/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.azure.dev.api.model.WorkItemFieldReference;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Base field instance for workItemType fields.
 */
@ApiModel(description = "Base field instance for workItemType fields.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-08-21T10:09:21.598267402Z[Etc/UTC]")
public class WorkItemTypeFieldInstanceBase {
  public static final String SERIALIZED_NAME_ALWAYS_REQUIRED = "alwaysRequired";
  @SerializedName(SERIALIZED_NAME_ALWAYS_REQUIRED)
  private Boolean alwaysRequired;

  public static final String SERIALIZED_NAME_DEPENDENT_FIELDS = "dependentFields";
  @SerializedName(SERIALIZED_NAME_DEPENDENT_FIELDS)
  private List<WorkItemFieldReference> dependentFields = null;

  public static final String SERIALIZED_NAME_HELP_TEXT = "helpText";
  @SerializedName(SERIALIZED_NAME_HELP_TEXT)
  private String helpText;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_REFERENCE_NAME = "referenceName";
  @SerializedName(SERIALIZED_NAME_REFERENCE_NAME)
  private String referenceName;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public WorkItemTypeFieldInstanceBase alwaysRequired(Boolean alwaysRequired) {
    
    this.alwaysRequired = alwaysRequired;
    return this;
  }

   /**
   * Indicates whether field value is always required.
   * @return alwaysRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates whether field value is always required.")

  public Boolean getAlwaysRequired() {
    return alwaysRequired;
  }


  public void setAlwaysRequired(Boolean alwaysRequired) {
    this.alwaysRequired = alwaysRequired;
  }


  public WorkItemTypeFieldInstanceBase dependentFields(List<WorkItemFieldReference> dependentFields) {
    
    this.dependentFields = dependentFields;
    return this;
  }

  public WorkItemTypeFieldInstanceBase addDependentFieldsItem(WorkItemFieldReference dependentFieldsItem) {
    if (this.dependentFields == null) {
      this.dependentFields = new ArrayList<WorkItemFieldReference>();
    }
    this.dependentFields.add(dependentFieldsItem);
    return this;
  }

   /**
   * The list of dependent fields.
   * @return dependentFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list of dependent fields.")

  public List<WorkItemFieldReference> getDependentFields() {
    return dependentFields;
  }


  public void setDependentFields(List<WorkItemFieldReference> dependentFields) {
    this.dependentFields = dependentFields;
  }


  public WorkItemTypeFieldInstanceBase helpText(String helpText) {
    
    this.helpText = helpText;
    return this;
  }

   /**
   * Gets the help text for the field.
   * @return helpText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gets the help text for the field.")

  public String getHelpText() {
    return helpText;
  }


  public void setHelpText(String helpText) {
    this.helpText = helpText;
  }


  public WorkItemTypeFieldInstanceBase name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The friendly name of the field.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The friendly name of the field.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WorkItemTypeFieldInstanceBase referenceName(String referenceName) {
    
    this.referenceName = referenceName;
    return this;
  }

   /**
   * The reference name of the field.
   * @return referenceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The reference name of the field.")

  public String getReferenceName() {
    return referenceName;
  }


  public void setReferenceName(String referenceName) {
    this.referenceName = referenceName;
  }


  public WorkItemTypeFieldInstanceBase url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * The REST URL of the resource.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The REST URL of the resource.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkItemTypeFieldInstanceBase workItemTypeFieldInstanceBase = (WorkItemTypeFieldInstanceBase) o;
    return Objects.equals(this.alwaysRequired, workItemTypeFieldInstanceBase.alwaysRequired) &&
        Objects.equals(this.dependentFields, workItemTypeFieldInstanceBase.dependentFields) &&
        Objects.equals(this.helpText, workItemTypeFieldInstanceBase.helpText) &&
        Objects.equals(this.name, workItemTypeFieldInstanceBase.name) &&
        Objects.equals(this.referenceName, workItemTypeFieldInstanceBase.referenceName) &&
        Objects.equals(this.url, workItemTypeFieldInstanceBase.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alwaysRequired, dependentFields, helpText, name, referenceName, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkItemTypeFieldInstanceBase {\n");
    sb.append("    alwaysRequired: ").append(toIndentedString(alwaysRequired)).append("\n");
    sb.append("    dependentFields: ").append(toIndentedString(dependentFields)).append("\n");
    sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    referenceName: ").append(toIndentedString(referenceName)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

