/*
 * WorkItemTracking
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 6.1-preview
 * Contact: nugetvss@microsoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.azure.dev.api;

import com.azure.dev.api.ApiCallback;
import com.azure.dev.api.ApiClient;
import com.azure.dev.api.ApiException;
import com.azure.dev.api.ApiResponse;
import com.azure.dev.api.Configuration;
import com.azure.dev.api.Pair;
import com.azure.dev.api.ProgressRequestBody;
import com.azure.dev.api.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.util.UUID;
import com.azure.dev.api.model.Wiql;
import com.azure.dev.api.model.WorkItemQueryResult;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WiqlApi {
    private ApiClient localVarApiClient;

    public WiqlApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WiqlApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for wiqlGet
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlGetCall(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{organization}/{project}/{team}/_apis/wit/wiql/{id}"
            .replaceAll("\\{" + "organization" + "\\}", localVarApiClient.escapeString(organization.toString()))
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()))
            .replaceAll("\\{" + "project" + "\\}", localVarApiClient.escapeString(project.toString()))
            .replaceAll("\\{" + "team" + "\\}", localVarApiClient.escapeString(team.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (timePrecision != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timePrecision", timePrecision));
        }

        if ($top != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$top", $top));
        }

        if (apiVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("api-version", apiVersion));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "accessToken" };
        return localVarApiClient.buildCall(localVarPath, "HEAD", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call wiqlGetValidateBeforeCall(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organization' is set
        if (organization == null) {
            throw new ApiException("Missing the required parameter 'organization' when calling wiqlGet(Async)");
        }
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling wiqlGet(Async)");
        }
        
        // verify the required parameter 'project' is set
        if (project == null) {
            throw new ApiException("Missing the required parameter 'project' when calling wiqlGet(Async)");
        }
        
        // verify the required parameter 'team' is set
        if (team == null) {
            throw new ApiException("Missing the required parameter 'team' when calling wiqlGet(Async)");
        }
        
        // verify the required parameter 'apiVersion' is set
        if (apiVersion == null) {
            throw new ApiException("Missing the required parameter 'apiVersion' when calling wiqlGet(Async)");
        }
        

        okhttp3.Call localVarCall = wiqlGetCall(organization, id, project, team, apiVersion, timePrecision, $top, _callback);
        return localVarCall;

    }

    /**
     * 
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return Integer
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public Integer wiqlGet(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top) throws ApiException {
        ApiResponse<Integer> localVarResp = wiqlGetWithHttpInfo(organization, id, project, team, apiVersion, timePrecision, $top);
        return localVarResp.getData();
    }

    /**
     * 
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return ApiResponse&lt;Integer&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Integer> wiqlGetWithHttpInfo(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top) throws ApiException {
        okhttp3.Call localVarCall = wiqlGetValidateBeforeCall(organization, id, project, team, apiVersion, timePrecision, $top, null);
        Type localVarReturnType = new TypeToken<Integer>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlGetAsync(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback<Integer> _callback) throws ApiException {

        okhttp3.Call localVarCall = wiqlGetValidateBeforeCall(organization, id, project, team, apiVersion, timePrecision, $top, _callback);
        Type localVarReturnType = new TypeToken<Integer>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for wiqlQueryById
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlQueryByIdCall(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/{organization}/{project}/{team}/_apis/wit/wiql/{id}"
            .replaceAll("\\{" + "organization" + "\\}", localVarApiClient.escapeString(organization.toString()))
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()))
            .replaceAll("\\{" + "project" + "\\}", localVarApiClient.escapeString(project.toString()))
            .replaceAll("\\{" + "team" + "\\}", localVarApiClient.escapeString(team.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (timePrecision != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timePrecision", timePrecision));
        }

        if ($top != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$top", $top));
        }

        if (apiVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("api-version", apiVersion));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call wiqlQueryByIdValidateBeforeCall(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organization' is set
        if (organization == null) {
            throw new ApiException("Missing the required parameter 'organization' when calling wiqlQueryById(Async)");
        }
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling wiqlQueryById(Async)");
        }
        
        // verify the required parameter 'project' is set
        if (project == null) {
            throw new ApiException("Missing the required parameter 'project' when calling wiqlQueryById(Async)");
        }
        
        // verify the required parameter 'team' is set
        if (team == null) {
            throw new ApiException("Missing the required parameter 'team' when calling wiqlQueryById(Async)");
        }
        
        // verify the required parameter 'apiVersion' is set
        if (apiVersion == null) {
            throw new ApiException("Missing the required parameter 'apiVersion' when calling wiqlQueryById(Async)");
        }
        

        okhttp3.Call localVarCall = wiqlQueryByIdCall(organization, id, project, team, apiVersion, timePrecision, $top, _callback);
        return localVarCall;

    }

    /**
     * 
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return WorkItemQueryResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public WorkItemQueryResult wiqlQueryById(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top) throws ApiException {
        ApiResponse<WorkItemQueryResult> localVarResp = wiqlQueryByIdWithHttpInfo(organization, id, project, team, apiVersion, timePrecision, $top);
        return localVarResp.getData();
    }

    /**
     * 
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return ApiResponse&lt;WorkItemQueryResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkItemQueryResult> wiqlQueryByIdWithHttpInfo(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top) throws ApiException {
        okhttp3.Call localVarCall = wiqlQueryByIdValidateBeforeCall(organization, id, project, team, apiVersion, timePrecision, $top, null);
        Type localVarReturnType = new TypeToken<WorkItemQueryResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Gets the results of the query given the query ID.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param id The query ID. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlQueryByIdAsync(String organization, UUID id, String project, String team, String apiVersion, Boolean timePrecision, Integer $top, final ApiCallback<WorkItemQueryResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = wiqlQueryByIdValidateBeforeCall(organization, id, project, team, apiVersion, timePrecision, $top, _callback);
        Type localVarReturnType = new TypeToken<WorkItemQueryResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for wiqlQueryByWiql
     * @param organization The name of the Azure DevOps organization. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param body The query containing the WIQL. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlQueryByWiqlCall(String organization, String project, String team, String apiVersion, Wiql body, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/{organization}/{project}/{team}/_apis/wit/wiql"
            .replaceAll("\\{" + "organization" + "\\}", localVarApiClient.escapeString(organization.toString()))
            .replaceAll("\\{" + "project" + "\\}", localVarApiClient.escapeString(project.toString()))
            .replaceAll("\\{" + "team" + "\\}", localVarApiClient.escapeString(team.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (timePrecision != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("timePrecision", timePrecision));
        }

        if ($top != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$top", $top));
        }

        if (apiVersion != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("api-version", apiVersion));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "oauth2" };
        return localVarApiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call wiqlQueryByWiqlValidateBeforeCall(String organization, String project, String team, String apiVersion, Wiql body, Boolean timePrecision, Integer $top, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'organization' is set
        if (organization == null) {
            throw new ApiException("Missing the required parameter 'organization' when calling wiqlQueryByWiql(Async)");
        }
        
        // verify the required parameter 'project' is set
        if (project == null) {
            throw new ApiException("Missing the required parameter 'project' when calling wiqlQueryByWiql(Async)");
        }
        
        // verify the required parameter 'team' is set
        if (team == null) {
            throw new ApiException("Missing the required parameter 'team' when calling wiqlQueryByWiql(Async)");
        }
        
        // verify the required parameter 'apiVersion' is set
        if (apiVersion == null) {
            throw new ApiException("Missing the required parameter 'apiVersion' when calling wiqlQueryByWiql(Async)");
        }
        
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling wiqlQueryByWiql(Async)");
        }
        

        okhttp3.Call localVarCall = wiqlQueryByWiqlCall(organization, project, team, apiVersion, body, timePrecision, $top, _callback);
        return localVarCall;

    }

    /**
     * 
     * Gets the results of the query given its WIQL.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param body The query containing the WIQL. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return WorkItemQueryResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public WorkItemQueryResult wiqlQueryByWiql(String organization, String project, String team, String apiVersion, Wiql body, Boolean timePrecision, Integer $top) throws ApiException {
        ApiResponse<WorkItemQueryResult> localVarResp = wiqlQueryByWiqlWithHttpInfo(organization, project, team, apiVersion, body, timePrecision, $top);
        return localVarResp.getData();
    }

    /**
     * 
     * Gets the results of the query given its WIQL.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param body The query containing the WIQL. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @return ApiResponse&lt;WorkItemQueryResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WorkItemQueryResult> wiqlQueryByWiqlWithHttpInfo(String organization, String project, String team, String apiVersion, Wiql body, Boolean timePrecision, Integer $top) throws ApiException {
        okhttp3.Call localVarCall = wiqlQueryByWiqlValidateBeforeCall(organization, project, team, apiVersion, body, timePrecision, $top, null);
        Type localVarReturnType = new TypeToken<WorkItemQueryResult>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Gets the results of the query given its WIQL.
     * @param organization The name of the Azure DevOps organization. (required)
     * @param project Project ID or project name (required)
     * @param team Team ID or team name (required)
     * @param apiVersion Version of the API to use.  This should be set to &#39;6.1-preview.2&#39; to use this version of the api. (required)
     * @param body The query containing the WIQL. (required)
     * @param timePrecision Whether or not to use time precision. (optional)
     * @param $top The max number of results to return. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call wiqlQueryByWiqlAsync(String organization, String project, String team, String apiVersion, Wiql body, Boolean timePrecision, Integer $top, final ApiCallback<WorkItemQueryResult> _callback) throws ApiException {

        okhttp3.Call localVarCall = wiqlQueryByWiqlValidateBeforeCall(organization, project, team, apiVersion, body, timePrecision, $top, _callback);
        Type localVarReturnType = new TypeToken<WorkItemQueryResult>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
